owner: owner-placeholder
git-repo: repo-placeholder
charts-repo-url: https://owner-placeholder.github.io/repo-placeholder
target-branch: gh-pages
package-path: .cr-release-packages
index-path: .cr-index
release-name-template: "{{ .Name }}-{{ .Version }}"
