security:
  # Safety policy file for k8s-chat backend
  # This file defines exceptions for security vulnerabilities that cannot be immediately resolved

  # Ignore specific vulnerability IDs (use safety vulnerability IDs, not CVE numbers)
  ignore-vulnerabilities:
    # Add specific vulnerability IDs here if needed after security review
    # Example: 12345  # Brief justification for exception

  # Ignore based on CVSS severity (0.0-10.0 scale, where 7.0+ is high, 4.0-6.9 is medium)
  ignore-cvss-severity-below: 7.0
  
  # Handle unknown severity vulnerabilities
  ignore-cvss-unknown-severity: false
  
  # Continue on vulnerability errors (don't fail build)
  continue-on-vulnerability-error: false
  
  # Ignore unpinned requirements warnings
  ignore-unpinned-requirements: true

# Comments and notes (not parsed by safety but useful for documentation)
# Security policy metadata for demo-k8s-chat application
#
# Last reviewed: 2025-11-23
# Reviewer: Security Team
# 
# Notes:
# - This is a demonstration application - some risks are acceptable
# - Goose-AI and Kubernetes deps need flexibility for compatibility  
# - All critical security fixes have been applied
# - Regular security reviews scheduled
#
# Vulnerability remediation summary:
# - FastAPI: Updated to 0.110.0 (from 0.104.1) - Fixed CVE-2024-24762, PVE-2024-64930
# - aiohttp: Updated to 3.12.14 (from 3.9.1) - Fixed multiple CVEs
# - orjson: Updated to 3.9.15 (from 3.9.10) - Fixed CVE-2024-27454  
# - black: Updated to 24.3.0 (from 23.11.0) - Fixed CVE-2024-21503
#
# Dependencies that are intentionally unpinned:
# - goose-ai: Framework in active development, need latest features
# - kubernetes: Need compatibility across different K8s versions
